name: Update our EC2 instance
on:
  push:
    branches:
      - master
jobs:
  update:
    name: Prod - SSH Login, Pull, Reload
    runs-on: ubuntu-latest
    steps:
      - name: Execute
        uses: appleboy/ssh-action@v0.1.4
        with:
          script: |
            cd api
            git checkout master
            npm install
            ./prisma-generate
            pm2 reload all
          host: http://ec2-34-203-72-107.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ secrets.API_PRIVATE_KEY }}